### ISSUE TITLE
Entry update error

### ISSUE THREAD

**Issue by rumca-js** [rumca-js/Django-link-archive#208]
Traceback (most recent call last):
  File "/home/rumpel/WorkDir/DjangoPage/linklibrary/rsshistory/threadhandlers.py", line 173, in process
    u.update_data()
  File "/home/rumpel/WorkDir/DjangoPage/linklibrary/rsshistory/controllers/entriesutils.py", line 526, in update_data
    p = url.p
AttributeError: 'EntryUrlInterface' object has no attribute 'p'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rumpel/WorkDir/DjangoPage/linklibrary/rsshistory/threadhandlers.py", line 1274, in process_one_for_all
    if handler and handler.process(obj):
  File "/home/rumpel/WorkDir/DjangoPage/linklibrary/rsshistory/threadhandlers.py", line 184, in process
    info_text = "Exception when updating link data {0} {1} {2}".format(obj.subject)
IndexError: Replacement index 1 out of range for positional args tuple

**Comment by rumca-js** [comment]
Fixed
